config/routes.rb
Rails.application.routes.draw do
  resources :shorteners do
    get 'clip/:slug' => 'shorteners#clip', as: :clip, on: :collection
  end
  resources :resumes

  root 'welcome#index'

end

app/models/resume.rb
require 'digest/md5'

class Resume < ActiveRecord::Base
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :email, uniqueness: true
  validates :cv, presence: true

  def fullname
    [firstname, lastname].join(' ')
  end

  def gravatar_hash
    Digest::MD5.hexdigest(email.downcase)
  end
end

app/models/shortener.rb
class Shortener < ActiveRecord::Base
  validates :url, presence: true
  validates_format_of :url, :with => URI::regexp(%w(http https))

  before_save :set_slug

  private

  def set_slug
    self.slug = Digest::SHA1.hexdigest(self.url)[0..8]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]

  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
    @cv = JSON.parse(@resume.cv)
    @profile = @cv['profile']
    @experiences = @cv['cv']['experiences']
    @trainings = @cv['cv']['trainings']
    @educations = @cv['cv']['educations']
    @portfolios = @cv['cv']['portfolios']
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(resume_params)

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1
  # PATCH/PUT /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url, notice: 'Resume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.require(:resume).permit(:firstname, :lastname, :email, :cv)
    end
end

app/controllers/shorteners_controller.rb
class ShortenersController < ApplicationController
  before_action :set_shortener, only: [:show, :edit, :update, :destroy]

  # GET /shorteners
  # GET /shorteners.json
  def index
    @shorteners = Shortener.all
  end

  # GET /shorteners/1
  # GET /shorteners/1.json
  def show
  end

  # GET /shorteners/new
  def new
    @shortener = Shortener.new
  end

  # GET /shorteners/1/edit
  def edit
  end

  def clip
    @shortener = Shortener.where(slug: params[:slug]).first

    if @shortener
      redirect_to @shortener.url
    else
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  # POST /shorteners
  # POST /shorteners.json
  def create
    @shortener = Shortener.new(shortener_params)

    respond_to do |format|
      if @shortener.save
        format.html { redirect_to @shortener, notice: 'Shortener was successfully created.' }
        format.json { render :show, status: :created, location: @shortener }
      else
        format.html { render :new }
        format.json { render json: @shortener.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shorteners/1
  # PATCH/PUT /shorteners/1.json
  def update
    respond_to do |format|
      if @shortener.update(shortener_params)
        format.html { redirect_to @shortener, notice: 'Shortener was successfully updated.' }
        format.json { render :show, status: :ok, location: @shortener }
      else
        format.html { render :edit }
        format.json { render json: @shortener.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shorteners/1
  # DELETE /shorteners/1.json
  def destroy
    @shortener.destroy
    respond_to do |format|
      format.html { redirect_to shorteners_url, notice: 'Shortener was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shortener
      @shortener = Shortener.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shortener_params
      params.require(:shortener).permit(:url, :slug)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/shorteners_helper.rb
module ShortenersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SwdApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script></head>
<body>

  <div class="container">
    <div class="header clearfix">
      <nav>
        <ul class="nav nav-pills pull-right">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Resumes', resumes_path %></li>
          <li><%= link_to 'URL Shortener', shorteners_path %></li>
        </ul>
      </nav>
      <h3 class="text-muted">SWD App</h3>
    </div>

    <div class="row marketing">
      <div class="col-lg-12">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/resumes/_form.html.erb
<%= form_for(@resume) do |f| %>
  <% if @resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% @resume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :cv %><br>
    <%= f.text_area :cv %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resumes/edit.html.erb
<h1>Editing Resume</h1>

<%= render 'form' %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

app/views/resumes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Resumes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.firstname %></td>
        <td><%= resume.lastname %></td>
        <td><%= resume.email %></td>
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resume', new_resume_path, class: 'btn btn-default' %>

app/views/resumes/new.html.erb
<h1>New Resume</h1>

<%= render 'form' %>

<%= link_to 'Back', resumes_path %>

app/views/resumes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <img src="//gravatar.com/avatar/<%= @resume.gravatar_hash %>" />
</p>

<h2>
  <%= @resume.fullname %>
  <%= @profile['email'] %>
  <%= @profile['mobile_no'] %>
</h2>

<h3>
  Professional Experience
</h3>

<% @experiences.each do |exp| %>
  <h4>
    <%= exp['title'] %> / <%= exp['company'] %> &mdash; <%= exp['location'] %>
    <%= exp['started'] %> &ndash; <%= exp['ended'] %>
  </h4>

  <p>
    <%= exp['description'] %>
  </p>
<% end %>

<h3>
  Professional Training
</h3>

<% @trainings.each do |trn| %>
  <h4>
    <%= trn['title'] %> / <%= trn['location'] %>
    <%= trn['started'] %> &ndash; <%= trn['ended'] %>
  </h4>

  <p>
    <%= trn['details'] %>
  </p>
<% end %>

<h3>
  Education
</h3>

<% @educations.each do |edu| %>
  <h4>
    <%= edu['course'] %> / <%= edu['place'] %>
    <%= edu['graduated_in'] %>
  </h4>

  <p>
    <%= edu['degree'] %>
  </p>
<% end %>

<h3>
  Portfolios
</h3>

<% @portfolios.each do |pfl| %>
  <h4>
    <%= pfl['title'] %>
  </h4>
  <p>
    <%= pfl['details'] %>
  </p>
<% end %>

<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resumes_path %>

app/views/shorteners/_form.html.erb
<%= form_for(@shortener) do |f| %>
  <% if @shortener.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shortener.errors.count, "error") %> prohibited this shortener from being saved:</h2>

      <ul>
      <% @shortener.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shorteners/edit.html.erb
<h1>Editing Shortener</h1>

<%= render 'form' %>

<%= link_to 'Show', @shortener %> |
<%= link_to 'Back', shorteners_path %>

app/views/shorteners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shorteners</h1>

<table class="table">
  <thead>
    <tr>
      <th>Url</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shorteners.each do |shortener| %>
      <tr>
        <td>
          <%= shortener.url %><br>
          <small class="text-muted">clip: <%= clip_shorteners_url(shortener.slug) %></small>
        </td>
        <td><%= link_to 'ClipIt!', clip_shorteners_path(shortener.slug), target: '_blank' %></td>
        <td><%= link_to 'Show', shortener %></td>
        <td><%= link_to 'Edit', edit_shortener_path(shortener) %></td>
        <td><%= link_to 'Destroy', shortener, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shortener', new_shortener_path, class: 'btn btn-default' %>

app/views/shorteners/new.html.erb
<h1>New Shortener</h1>

<%= render 'form' %>

<%= link_to 'Back', shorteners_path %>

app/views/shorteners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @shortener.url %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @shortener.slug %>
</p>

<%= link_to 'Edit', edit_shortener_path(@shortener) %> |
<%= link_to 'Back', shorteners_path %>

app/views/welcome/index.html.erb
<h4>Resume in JSON format</h4>
<p>TODO: Your resume/CV in JSON format and a parser for the resume so it can be displayed<br>
  visit: <%= link_to resumes_url, resumes_path %></p>

<h4>tic-tac-toe in ruby</h4>
<p>TODO: Write a tic-tac-toe app that never loses on a 3x3 board<br>
  run in terminal: <code>ruby lib/tictactoe.rb</code> by cloning: <code>https://github.com/nurulazradm/swd-app/tree/tictactoe</code></p>

<h4>URL Shortener</h4>
<p>TODO: Write a URL shortener app<br>
  visit: <%= link_to shorteners_url, shorteners_path %></p>